Add initial code base for a common repository for coding standards
matomo-org/matomo-coding-standards pull request #1
Opened 2024-06-24 07:58 UTC by AltamashShaikh

### Description:

Add initial code base for a common repository for coding standards

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

2024-06-24 13:17 UTC, michalkleiner commented on README.md
Do we need to have the paths in the instructions?
Normally we would include this repository as a dev dependency in projects/plugins composer.json and then have composer script e.g. `codecheck` (which you'd run via `composer codecheck` and all the necessary paths would be either default or defined in the composer script params.

So we should suggest, if anything, how to add a composer script line for a given plugin. Most of the times I don't expect we'd need any specific config as all composer scripts run primarily in the folder where composer.json file is located.

2024-06-24 13:17 UTC, michalkleiner commented on Standard/GoogleAnalyticsImporter/phpcs.xml
if this is the default phpcs.xml, it should be in the folder. We don't need specific plugin names or folders in the path to the default phpcs.xml

2024-06-24 13:18 UTC, michalkleiner commented on Standard/GoogleAnalyticsImporter/phpcs.xml
we will have a default here, one that covers as much as possible, and then any customisations would be made in module's (plugin's) repo.

2024-06-24 13:18 UTC, michalkleiner commented on composer.json
> +    "name": "altamash/matomo-coding-standards",
```suggestion
    "name": "matomo-org/matomo-coding-standards",
```

2024-06-25 01:20 UTC, AltamashShaikh commented on Standard/GoogleAnalyticsImporter/phpcs.xml
@michalkleiner Its just a skeleton to decide how we want this repository to be.

2024-06-25 01:21 UTC, AltamashShaikh commented on README.md
I just added that, so that its easier for reviewer to run and check, we can tweak this.

2024-06-26 09:19 UTC, sgiehl requested changes
Left a couple of comments with things that imho should be changed in global phpcs ruleset.
Once this global ruleset is finished, we can start using it in repo local phpcs files.

2024-06-26 09:19 UTC, sgiehl commented on Standard/GoogleAnalyticsImporter/phpcs.xml
As this should be a global ruleset the file should be named `Matomo/ruleset.xml`.

2024-06-26 09:19 UTC, sgiehl commented on Standard/GoogleAnalyticsImporter/phpcs.xml
> +    <description>Matomo Coding Standard for GoogleAnalyticsImporter plugin</description>
```suggestion
    <description>Matomo Coding Standard</description>
```

2024-06-26 09:19 UTC, sgiehl commented on Standard/GoogleAnalyticsImporter/phpcs.xml
> +    <exclude-pattern>plugins/(AnonymousPiwikUsageMeasurement|Bandwidth|CustomAlerts|CustomVariables|DeviceDetectorCache|LogViewer|LoginLdap|MarketingCampaignsReporting|Provider|QueuedTracking|Securit
In the default ruleset we should only exclude vendor and maybe lib. If core or a certain plugin needs additional exclude, they need to be defined in the according repo

```suggestion
    <exclude-pattern>*/vendor/*</exclude-pattern>
    <exclude-pattern>*/libs/*</exclude-pattern>
```

2024-06-26 09:19 UTC, sgiehl commented on Standard/GoogleAnalyticsImporter/phpcs.xml
> +        <exclude name="Squiz.WhiteSpace.ControlStructureSpacing.SpacingAfterOpen" />
we have meanwhile removed those in core. 

```suggestion
```

2024-06-26 09:19 UTC, sgiehl commented on Standard/GoogleAnalyticsImporter/phpcs.xml
> +        <exclude-pattern>plugins/*/Updates/*</exclude-pattern>
To make that working in core and plugin repos we should change that to
```suggestion
        <exclude-pattern>*/Updates/*</exclude-pattern>
```

2024-06-26 09:19 UTC, sgiehl commented on Standard/GoogleAnalyticsImporter/phpcs.xml
> +    </rule>
As those rules should be activated at some point, we should remove those from the global ruleset and add it to the ones in each repo, as long as needed.

2024-06-26 09:19 UTC, sgiehl commented on composer.json
> +        "phpstan/phpdoc-parser": "~1.24.0"
Those should be moved to `require` instead of `require-dev`

2024-06-26 09:56 UTC, AltamashShaikh commented
> Left a couple of comments with things that imho should be changed in global phpcs ruleset. Once this global ruleset is finished, we can start using it in repo local phpcs files.

@sgiehl I copied the one I created for GAImporter plugin, I should copy the one we have in [core](https://github.com/matomo-org/matomo/blob/5.x-dev/phpcs.xml) right ?

2024-06-26 12:09 UTC, sgiehl commented
No. It needs to be different from core one as well

2024-07-03 01:55 UTC, AltamashShaikh commented
@sgiehl @michalkleiner Does this look good to you guys now ??

2024-07-03 07:59 UTC, sgiehl commented
@AltamashShaikh I would actually remove the plugin specific file here. The repo should only contain the base ruleset we want to use. In addition we can consider to add custom sniffs at some point when needed.
Every additional stuff for adjusting used rules or excluding additional files should then be handled by `phpcs.xml` files in the according repo. E.g. for core that could then look like this: https://github.com/matomo-org/matomo/compare/use_matomo_cs

2024-07-03 08:17 UTC, AltamashShaikh commented
@sgiehl Removed plugin specific coding standard, we need to make this repository public before merging in core, do you have access to do the needful ?

2024-07-03 08:20 UTC, sgiehl commented
@AltamashShaikh No I don't have access to do that.

2024-07-03 08:21 UTC, AltamashShaikh commented
@caddoo Can you make this repository public ?

2024-07-03 12:11 UTC, michalkleiner commented
We should also change the default branch to `main` (inclusive naming) and when this is merged tag it as `0.0.1` or similar so that we use a version such as `~0.0.1`, not a branch.

2024-07-03 12:13 UTC, michalkleiner commented on Matomo/ruleset.xml
> +    <!-- Use PSR 12 standard as default -->
```suggestion
    <!-- Use PSR-12 standard as default -->
```

2024-07-03 12:17 UTC, michalkleiner commented on composer.json
> +    "description": "PHP CodeSniffer ruleset implementing the Matomo coding standards extending PSR12 coding standards.",
This repo will grow to also include front-end CS and other rules, so we should describe the package in a generic way.
```suggestion
    "description": "Coding standards for Matomo",
```

2024-07-04 02:07 UTC, AltamashShaikh commented on composer.json
> +    "description": "PHP CodeSniffer ruleset implementing the Matomo coding standards extending PSR12 coding standards.",
@michalkleiner Makes sense :+1: , updated as suggested

2024-07-19 01:16 UTC, AltamashShaikh commented
@tsteur Will you be able to make this repository public ?

2024-07-19 07:59 UTC, tsteur commented
That's done @AltamashShaikh

2024-07-19 08:01 UTC, AltamashShaikh commented
@sgiehl Can we merge this PR now and start using in core and extending the same for all the plugins ?

2024-07-19 08:27 UTC, sgiehl commented
@AltamashShaikh I'll merge this now and see if it works as expected when used in core.

2024-07-19 08:27 UTC, merged